# Build settings
gems:
  - jemoji
  - jekyll-paginate

# Site settings
title: "Ride"
description: > # this means to ignore newlines until "email:"
 We use slowcomotion to view the world from the perspective of our unique tandem recumbent. We love exploring counties using the path less traveled.  This blog captures many of our memories.  
email: ride@whitings.org 
#blog logo
logo: "/assets/images/ride.png"
float_logo: "/assets/images/bike.png"
#float_logo: true # true, false (default)

# blog cover
cover: "https://lh3.googleusercontent.com/pw/AP1GczNRWKumolpwVFteuVNVH36rLeGxASAT23iNSSJVL3kjJ_VDgzPpfVKiNl12bgdml2-aD9yUhe5LuTwZlAH6OoBq38iX-pB49N_HZ8vetOifIfSCJG_x=w1800-h630-p-k"


name: 'Pete and Natalie Whiting'
author: 'Pete and Natalie'
author_image: "/assets/images/author.jpg"

paginate:	15

url: "http://ride.whitings.org" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
#twitter_handle: '@dirkfabisch'

#fill in disqus shortname to use disqus
#disqus: ride-whitings-org

#google_analytics: UA-XXXXX-X

# social icons and sharing options
social:
#  - icon:	twitter
#    url:	https://twitter.com/dirkfabisch
#    desc: Follow me on twitter
#    share_url: http://twitter.com/share
#    share_title: ?text=
#    share_link: "&amp;url="

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: https://www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

#  - icon:	github
#    url:	https://github.com/dirkfabisch
#    desc:	Fork me on github
#    share_url:
#    share_title:
#    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
